### ISSUE TITLE
Debug toolbar 3.1.1 and WinterCms dev-develop working

### ISSUE THREAD

**Issue by Istislav** [wintercms/wn-debugbar-plugin#7] opened 2021-07-28 11:30 UTC
Hi, guys!

I wanted to run debug panel for my site and I could not do it, because It was not working correctly.
I had an absolutely non-clickable screen and cursor with top-bottom arrays.

I have found what you need to do to fix bugs and to make bar working:
1)css:
 .phpdebugbar-drag-capture {
    display: none !important;
}

After this change the screen is working 
But tabs are not working. So:

2) File debugbar.css - line 9:
Need to do this:
======== was ========
.phpdebugbar div,
.phpdebugbar-openhandler div {display:block}
======== need ========
.phpdebugbar div {}
.phpdebugbar-openhandler div {display:block}
================

After that debugbar tabs are working correctly.

Thank you for your attentions.
Thank you for your debugbar.

Your faithfully, Istislav

**Comment by LukeTowers** [comment] 2022-08-02 04:53
Closing this for now as it's probably fixed in the latest version, let me know if the issue is still present in the latest version.

**Closed by LukeTowers** 2022-08-02 04:53 UTC
Labels: Type: Unconfirmed Bug, Status: Review Needed
